alias pu='pushd'
alias po='popd'
alias ltr='ls -ltr'
alias la='ls -la'
alias cp='cp -rf'
alias hgrep='history | grep'
alias findtxt='find . -name *.* -print | xargs grep'
alias lock='gnome-screensaver-command -l'
alias vfind='find . -exec grep -q  '{}' \; -print'
alias trunc='cat /dev/null >'

alias heidi='wine /home/vee/workspace/development/heidi/heidisql.exe > ~/logs/heidi.log 2>&1 &'
alias mysql-console='mysql -h localhost -u root -ppassword'
alias tomcat_start='$TOMCAT_HOME/bin/startup.sh'
alias tomcat_shutdown='$TOMCAT_HOME/bin/shutdown.sh'
alias tomcat_restart='tomcat_shutdown;sleep 3;tomcat_start'
alias redis_start='sudo /etc/init.d/redis_6379 start'
alias redis_stop='sudo /etc/init.d/redis_6379 stop'
alias luke='java -jar ~/bin/lukeall-3.4.0.jar &'

alias g='cd ~/workspace/git-local-repo'
alias w='cd $HOME/workspace'

alias bastion='ssh nvenkiteswaran@54.164.91.168'
alias bastion-test='ssh nvenkiteswaran@54.225.69.88'
alias bastion-tel-test='ssh nvenkiteswaran@54.206.51.241'
alias bastion-tel='ssh nvenkiteswaran@54.79.13.89'
alias ssh_build='ssh -i .ssh/id_rsa nvenkiteswaran@ec2-23-22-252-170.compute-1.amazonaws.com'
alias a='cd ~/workspace/git-local-repo/AppDirect'
alias mysqlad='mysql --host=localhost --user=root --password=password appdirect'
alias samba='smbclient -U n.venkiteswaran \\batcave\test2'
